# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GraalVM Native Image build

on:
  push:
    branches: [ release ]
    tags: [ '*' ]

jobs:
  buildOnMac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.1.0
          native-image: true
      - name: Build with Maven
        run: mvn -B clean package -Dnative --file pom.xml
      - name: Run UPX
        uses: svenstaro/upx-action@v2
        with:
          file: bootstrap/target/bootstrap-1.0-SNAPSHOT-runner
          args: '-7'
      - name: Upload artifacts
        run: mkdir release && cp bootstrap/target/bootstrap-1.0-SNAPSHOT-runner release/slipbox-macos
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: release
